#!/usr/bin/env node
/* eslint-disable */

const fs = require("fs");
const path = require("path");
const readline = require("readline");

(async () => {
  const chalk = (await import("chalk")).default;
  console.log(
    chalk.cyan.bold("\n🚀 pwa-style-loader") +
      chalk.gray("\nby Abhisek Maiti") +
      chalk.gray("\nAdds vanilla CSS 🍦 support to Salesforce PWA Kit") +
      chalk.blue("\nGitHub: https://github.com/abhisekmaiti19") +
      chalk.magenta("\nLinkedIn: https://linkedin.com/in/abhisekmaiti19\n"),
  );
  const ROOT = process.cwd();
  const pkgPath = path.join(ROOT, "package.json");
  if (!fs.existsSync(pkgPath)) {
    console.log(chalk.red("❌ package.json not found."));
    console.log(
      chalk.gray("Please run this command from your project root.\n"),
    );
    process.exit(1);
  }

  let userPkg;
  try {
    userPkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  } catch {
    console.log(chalk.red("❌ Failed to parse package.json"));
    process.exit(1);
  }
  const isPwaKit =
    userPkg.ccExtensibility &&
    userPkg.ccExtensibility.extends === "@salesforce/retail-react-app";

  const hasRetailReactApp =
    (userPkg.devDependencies &&
      userPkg.devDependencies["@salesforce/retail-react-app"]) ||
    (userPkg.dependencies &&
      userPkg.dependencies["@salesforce/retail-react-app"]);

  if (!isPwaKit || !hasRetailReactApp) {
    console.log(
      chalk.red(
        "\n❌ This does not appear to be a Salesforce PWA Kit project.\n",
      ),
    );
    console.log(chalk.yellow("Expected in package.json:\n"));
    console.log(
      chalk.gray(`"ccExtensibility": {
              "extends": "@salesforce/retail-react-app"
            }
                    
            "devDependencies": {
              "@salesforce/retail-react-app": "x.x.x"
            }\n`),
    );
    process.exit(1);
  }

  console.log(chalk.green("✅ Salesforce PWA Kit project detected\n"));

  const WEBPACK_DEST = path.join(ROOT, "webpack.config.js");
  const POSTCSS_DEST = path.join(ROOT, "postcss.config.js");

  const WEBPACK_SRC = path.join(__dirname, "../webpack.config.js");
  const POSTCSS_SRC = path.join(__dirname, "../postcss.config.js");

  const webpackTemplate = fs.readFileSync(WEBPACK_SRC, "utf8");
  const postcssTemplate = fs.readFileSync(POSTCSS_SRC, "utf8");

  const BRAND = `
/**
 * Generated by pwa-style-loader
 * Author: Abhisek Maiti
 * GitHub: https://github.com/abhisekmaiti19
 * LinkedIn: https://linkedin.com/in/abhisekmaiti19
 */
`.trim();
  function askYesNo(question) {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    return new Promise((resolve) => {
      rl.question(question, (answer) => {
        rl.close();
        resolve(/^y(es)?$/i.test(answer.trim()));
      });
    });
  }
  async function createOrReplace({ dest, template, filename }) {
    if (!fs.existsSync(dest)) {
      fs.writeFileSync(dest, `${BRAND}\n\n${template}`);
      console.log(chalk.green(`✅ ${filename} created`));
      return;
    }

    console.log(chalk.yellow(`⚠️ ${filename} already exists.`));

    const replace = await askYesNo(
      chalk.cyan(`Do you want to replace ${filename}? (y/N): `),
    );

    if (!replace) {
      console.log(chalk.gray(`ℹ️ Skipped ${filename}. No changes made.`));
      return;
    }

    fs.writeFileSync(dest, `${BRAND}\n\n${template}`);
    console.log(chalk.green(`✅ ${filename} replaced successfully`));
  }
  await createOrReplace({
    dest: WEBPACK_DEST,
    template: webpackTemplate,
    filename: "webpack.config.js",
  });

  await createOrReplace({
    dest: POSTCSS_DEST,
    template: postcssTemplate,
    filename: "postcss.config.js",
  });

  console.log(chalk.green("\n🎉 Setup completed the installation!\n"));
})();
